source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/environment.conf

input {
    kb_layout = br
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

gestures {
    workspace_swipe_distance = 300
    workspace_swipe_invert = true
    gesture = 3, horizontal, workspace
}

general {
    gaps_in = 10
    gaps_out = 14
    border_size = 2
    col.active_border = rgba(C8A8E9ff) rgba(7EB8F7ff) 45deg
    col.inactive_border = rgba(2E2F3Eff)
    layout = dwindle
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    on_focus_under_fullscreen = 2
}

dwindle { pseudotile = true; preserve_split = true }
