exec-once = awww-daemon
exec-once = sleep 1 && awww img ~/.config/lune/wallpapers/default.jpg
exec-once = waybar
exec-once = swaync
exec-once = hypridle
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = wl-paste --watch cliphist store
exec-once = nm-applet --indicator
exec-once = blueman-applet
