# Lune OS — Environment Variables
# Variáveis necessárias para Wayland e apps

# ── Wayland ──────────────────────────────────────────────────
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# ── Qt ───────────────────────────────────────────────────────
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt6ct

# ── GTK ──────────────────────────────────────────────────────
env = GDK_BACKEND,wayland,x11
env = GTK_THEME,adw-gtk3-dark

# ── Electron / Chrome ────────────────────────────────────────
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# ── Cursor ───────────────────────────────────────────────────
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,24

# ── Wine (Lune binfmt) ───────────────────────────────────────
env = WINEPREFIX,/home/$USER/.wine-lune

# ── Misc ─────────────────────────────────────────────────────
env = MOZ_ENABLE_WAYLAND,1
env = SDL_VIDEODRIVER,wayland
env = _JAVA_AWT_WM_NONREPARENTING,1
env = CLUTTER_BACKEND,wayland
env = OZONE_PLATFORM,wayland
