windowrule = float on, match:class pavucontrol
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class org.gnome.Calculator
windowrule = center on, match:class pavucontrol
windowrule = opacity 0.95 0.85, match:class kitty
windowrule = suppress_event maximize, match:class .*

layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.3, match:namespace waybar
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.3, match:namespace rofi
